name: custom viz
on:  
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
#  workflow-dispatch:
#   inputs: 

jobs:
  build-and-publish:
    name: Build and Publish Nerdpack
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        # with:
        #  api_key: ${{secrets.NEW_RELIC_API_KEY}}
         
       
      - name: Install NR1 CLI
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash

      # - name: Change to Nerdpack directory
      #   run: cd 
      - name: Configure NR1 CLI API key
        run: nr1 profile:setup --api-key ${{secrets.NEW_RELIC_API_KEY}}
      

      - name: Publish Nerdpack
        run: nr1 nerdpack:publish
      

      - name: Subscribe Nerdpack
        run: nr1 nerdpack:subscribe
       