name: custom viz
on:  
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
#  workflow-dispatch:
#   inputs: 

jobs:
  build-and-publish:
    name: Build and Publish Nerdpack
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
       
      - name: Install NR1 CLI
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash

      # - name: Change to Nerdpack directory
      #   run: cd 

      - name: Publish Nerdpack
        run: nr1 nerdpack:publish
        with:
         api_key: ${{ secrets.NEW_RELIC_API_KEY }}
         account_id: 3930388

      - name: Subscribe Nerdpack
        run: nr1 nerdpack:subscribe
        with:
         api_key: ${{ secrets.NEW_RELIC_API_KEY }}
         account_id: 3930388