name: custom viz
on:  
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
#  workflow-dispatch:
#   inputs: 

jobs:
  build-and-publish:
    name: Build and Publish Nerdpack
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
        env:
          cache-name: node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}
    
      - name: Install NR1 CLI
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash

      - name: Publish Nerdpack
        run: nr1 nerdpack:publish

      - name: Subscribe Nerdpack
        run: nr1 nerdpack:subscribe